### ISSUE TITLE
Metadata TS Put

### ISSUE THREAD

**Issue by johannesscha** [BP-NFT-Game/NFT_Game#14]
Put Methode ersetzen durch Methode, die NFT Objekt bekommt ersetzen

**Comment by DeltaTecs** [comment]
Imlementiert durch [2f071182faf5c234a8a183b8d91004fb3a74c2dc](https://github.com/BP-NFT-Game/NFT_Game/commit/2f071182faf5c234a8a183b8d91004fb3a74c2dc)
