### ISSUE TITLE
NFT ID Vergabe Threadsafe

### ISSUE THREAD

**Issue by DeltaTecs** [BP-NFT-Game/NFT_Game#28]
Jetzige nft id generierung ist nicht threadsave.

Zu finden im Erdstall server interface

**Comment by DeltaTecs** [comment]
Wenn sich Id's doppeln oder übersprungen werden und dann doch metadaten in redis gepusht werden versucht redis den key selber hochzuzählen, dann ist alles im Arsch und die Metadatenbank muss neu aufgesetzt werden

**Comment by DeltaTecs** [comment]
geht übrigends mit
FLUSHDB 
FLUSHALL

**Comment by johannesscha** [comment]
Mit redis Methode getNFTCount() lösen
