### ISSUE TITLE
Dateiname für Sprites als Hash von big int

### ISSUE THREAD

**Issue by johannesscha** [BP-NFT-Game/NFT_Game#51]
Zahl auf 0-8, aA-zZ abbilden um zu lange Dateinamen zu verhindern

**Comment by DeltaTecs** [comment]
gewöhnlicher BigInt sollte in Dezimaldarstellung doch gehen: Benötigt 78+4 Zeichen, Maximale Linux Dateinamenlänge ist 255 chars (bytes)
