### ISSUE TITLE
Metadata.ts

### ISSUE THREAD

**Issue by johannesscha** [BP-NFT-Game/NFT_Game#6]
Metadata.ts die erweiterte Klasse löschen, dbprovider verwenden

**Comment by DeltaTecs** [comment]
Ich entwerf mal ne neue NFTMetadata

**Comment by DeltaTecs** [comment]
Momentanes NFTMetaServer beruht auf den Annahmen:

- tokenId (id) ist  global eindeutig
- Redis interface nimmt die tokenId als alleinigen primärschlüssel
- Redis interface hat eine getAllMetadata die jedes Paar {tokenId, ownerAddr, metaJSON} als Liste zurückgibt
- Transaktionen bedürfen keines Owner Updates... (dazu muss metadata_ext.ts überarbeitet werden aber vorher sollte sich die Datenstruktur klären (#13))
- es bedarf keiner weiteren Anbindung an ein erdstall NFT interface (Wahrscheinlich falsch, werde ich mir noch ansehen)

**Comment by DeltaTecs** [comment]
TODO:
- Datenschema abklären (#13)
- Datenbank Methoden ergänzen oder anpassen
- NFT interface Anbindung sicherstellen
- Dependencies korrigieren
- RawItemMetadata um geeignete Extentions oder eine Subklasse ergänzen
- Als Server integrieren
- Tests schreiben.......
